import colors from '../configs/MyColors';

export const blocks = [
  {id: 1, color: colors.first_13_weeksColor},
  {id: 2, color: colors.first_13_weeksColor},
  {id: 3, color: colors.first_13_weeksColor},
  {id: 4, color: colors.first_13_weeksColor},
  {id: 5, color: colors.first_13_weeksColor},
  {id: 6, color: colors.first_13_weeksColor},
  {id: 7, color: colors.first_13_weeksColor},
  {id: 8, color: colors.first_13_weeksColor},
  {id: 9, color: colors.first_13_weeksColor},
  {id: 10, color: colors.first_13_weeksColor},
  {id: 11, color: colors.first_13_weeksColor},
  {id: 12, color: colors.first_13_weeksColor},
  {id: 13, color: colors.first_13_weeksColor},

  {id: 14, color: colors.second_13_weeksColor},
  {id: 15, color: colors.second_13_weeksColor},
  {id: 16, color: colors.second_13_weeksColor},
  {id: 17, color: colors.second_13_weeksColor},
  {id: 18, color: colors.second_13_weeksColor},
  {id: 19, color: colors.second_13_weeksColor},
  {id: 20, color: colors.second_13_weeksColor},
  {id: 21, color: colors.second_13_weeksColor},
  {id: 22, color: colors.second_13_weeksColor},
  {id: 23, color: colors.second_13_weeksColor},
  {id: 24, color: colors.second_13_weeksColor},
  {id: 25, color: colors.second_13_weeksColor},
  {id: 26, color: colors.second_13_weeksColor},

  {id: 27, color: colors.final_13_weeksColor},
  {id: 28, color: colors.final_13_weeksColor},
  {id: 29, color: colors.final_13_weeksColor},
  {id: 30, color: colors.final_13_weeksColor},
  {id: 31, color: colors.final_13_weeksColor},
  {id: 32, color: colors.final_13_weeksColor},
  {id: 33, color: colors.final_13_weeksColor},
  {id: 34, color: colors.final_13_weeksColor},
  {id: 35, color: colors.final_13_weeksColor},
  {id: 36, color: colors.final_13_weeksColor},
  {id: 37, color: colors.final_13_weeksColor},
  {id: 38, color: colors.final_13_weeksColor},
  {id: 39, color: colors.final_13_weeksColor},

  {id: 40, color: colors.weekIndicatorColor},
];
