import colors from '../configs/MyColors';

export const menuList = [
  {name: 'প্রেগন্যান্সি শেষ করুন', id: 1},
  {name: 'পূর্বের ইতিহাস', id: 2},
  {name: 'এপটি শেয়ার করুন', id: 3},
  {name: 'মতামত দিন', id: 4},
  {name: 'About Us', id: 5},
  {name: 'Dismiss', id: 6},
];

export const currentData = [
  {id: 1, text: 'One week running..', audioName: ''},
  {id: 2, text: 'One week running..'},
  {id: 1, text: 'One week running..'},
  {id: 1, text: 'One week running..'},
  {id: 1, text: 'One week running..'},
  {id: 1, text: 'One week running..'},
  {id: 1, text: 'One week running..'},
  {id: 1, text: 'One week running..'},
  {id: 1, text: 'One week running..'},
  {id: 1, text: 'One week running..'},
  {id: 1, text: 'One week running..'},
  {id: 1, text: 'One week running..'},
  {id: 1, text: 'One week running..'},
  {id: 1, text: 'One week running..'},
  {id: 1, text: 'One week running..'},
  {id: 1, text: 'One week running..'},
  {id: 1, text: 'One week running..'},
  {id: 1, text: 'One week running..'},
];

export const songsList = [
  {id: 0, name: 'mysong2.mp3'},
  {id: 1, name: 'mysong1.mp3'},
  {id: 2, name: 'mysong2.mp3'},
  {id: 3, name: 'mysong1.mp3'},
  {id: 4, name: 'mysong2.mp3'},
  {id: 5, name: 'mysong1.mp3'},
  {id: 6, name: 'mysong2.mp3'},
  {id: 7, name: 'mysong1.mp3'},
  {id: 8, name: 'mysong2.mp3'},
  {id: 9, name: 'mysong1.mp3'},
  {id: 10, name: 'mysong2.mp3'},
  {id: 11, name: 'mysong1.mp3'},
  {id: 12, name: 'mysong2.mp3'},
  {id: 13, name: 'mysong1.mp3'},


  {id: 14, name: 'mysong2.mp3'},
  {id: 15, name: 'mysong1.mp3'},
  {id: 16, name: 'mysong2.mp3'},
  {id: 17, name: 'mysong1.mp3'},
  {id: 18, name: 'mysong2.mp3'},
  {id: 19, name: 'mysong1.mp3'},
  {id: 20, name: 'mysong2.mp3'},
  {id: 21, name: 'mysong1.mp3'},
  {id: 22, name: 'mysong2.mp3'},
  {id: 23, name: 'mysong1.mp3'},
  {id: 24, name: 'mysong2.mp3'},
  {id: 25, name: 'mysong1.mp3'},
  {id: 26, name: 'mysong2.mp3'},

  {id: 27, name: 'mysong1.mp3'},
  {id: 28, name: 'mysong2.mp3'},
  {id: 29, name: 'mysong1.mp3'},
  {id: 30, name: 'mysong2.mp3'},
  {id: 31, name: 'mysong1.mp3'},
  {id: 32, name: 'mysong2.mp3'},
  {id: 33, name: 'mysong1.mp3'},
  {id: 34, name: 'mysong2.mp3'},
  {id: 35, name: 'mysong1.mp3'},
  {id: 36, name: 'mysong2.mp3'},
  {id: 37, name: 'mysong1.mp3'},
  {id: 38, name: 'mysong2.mp3'},
  {id: 39, name: 'mysong1.mp3'},
];

export const blocks = [
  {id: 1, color: colors.first_13_weeksColor},
  {id: 2, color: colors.first_13_weeksColor},
  {id: 3, color: colors.first_13_weeksColor},
  {id: 4, color: colors.first_13_weeksColor},
  {id: 5, color: colors.first_13_weeksColor},
  {id: 6, color: colors.first_13_weeksColor},
  {id: 7, color: colors.first_13_weeksColor},
  {id: 8, color: colors.first_13_weeksColor},
  {id: 9, color: colors.first_13_weeksColor},
  {id: 10, color: colors.first_13_weeksColor},
  {id: 11, color: colors.first_13_weeksColor},
  {id: 12, color: colors.first_13_weeksColor},
  {id: 13, color: colors.first_13_weeksColor},

  {id: 14, color: colors.second_13_weeksColor},
  {id: 15, color: colors.second_13_weeksColor},
  {id: 16, color: colors.second_13_weeksColor},
  {id: 17, color: colors.second_13_weeksColor},
  {id: 18, color: colors.second_13_weeksColor},
  {id: 19, color: colors.second_13_weeksColor},
  {id: 20, color: colors.second_13_weeksColor},
  {id: 21, color: colors.second_13_weeksColor},
  {id: 22, color: colors.second_13_weeksColor},
  {id: 23, color: colors.second_13_weeksColor},
  {id: 24, color: colors.second_13_weeksColor},
  {id: 25, color: colors.second_13_weeksColor},
  {id: 26, color: colors.second_13_weeksColor},

  {id: 27, color: colors.final_13_weeksColor},
  {id: 28, color: colors.final_13_weeksColor},
  {id: 29, color: colors.final_13_weeksColor},
  {id: 30, color: colors.final_13_weeksColor},
  {id: 31, color: colors.final_13_weeksColor},
  {id: 32, color: colors.final_13_weeksColor},
  {id: 33, color: colors.final_13_weeksColor},
  {id: 34, color: colors.final_13_weeksColor},
  {id: 35, color: colors.final_13_weeksColor},
  {id: 36, color: colors.final_13_weeksColor},
  {id: 37, color: colors.final_13_weeksColor},
  {id: 38, color: colors.final_13_weeksColor},
  {id: 39, color: colors.final_13_weeksColor},

  {id: 40, color: colors.weekIndicatorColor},
];
